# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  android: circleci/android@2.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint:
    docker:
      - image: cimg/android:2022.09.2
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: v1a
      - restore_cache:
          keys:
            - v1a
      - run: ./gradlew detekt
      - android/save-gradle-cache:
          cache-prefix: v1a

  unit-tests:
    docker:
      - image: cimg/android:2022.09.2

    steps:
      - checkout
      - android/restore-build-cache:
          cache-prefix: v1a
      - android/restore-gradle-cache:
          cache-prefix: v1a
      - android/run-tests:
          test-command: ./gradlew testDebug
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - android/save-build-cache:
          cache-prefix: v1a
      - android/save-gradle-cache:
          cache-prefix: v1a
  ui-tests:
    executor:
      name: android/android-machine
      tag: 2022.06.1
      resource-class: large
    steps:
      - checkout
      - android/accept-licenses
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-33;google_apis;x86_64
      - android/restore-build-cache:
          cache-prefix: v1a
      - restore_cache:
          keys:
            - v1a
      - android/start-emulator:
          avd-name: myavd
          restore-gradle-cache-prefix: v1a
      - run: ./gradlew app:connectedCheck --console=plain
      - store_test_results:
          path: app/build/outputs/androidTest-results
      - store_artifacts:
          path: app/build/reports/androidTests/connected
      - android/kill-emulators
      - android/save-build-cache:
          cache-prefix: v1a
      - android/save-gradle-cache:
          cache-prefix: v1a

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  check:
    jobs:
      - lint
      - unit-tests
      - ui-tests
