[versions]
accompanist = "0.35.0-alpha"
androidGradlePlugin = "8.5.0-alpha06"
androidxActivity = "1.9.0-rc01"
androidxAnnotations = "1.8.0-beta01"
androidxBenchmark = "1.3.0-alpha02"
androidxCore = "1.13.0-rc01"
androidxDatastore = "1.1.0-rc01"
androidxGlance = "1.1.0-beta01"
androidxGlancePreview = "1.0.0-alpha06"
androidxLifecycle = "2.8.0-beta01"
androidxNavigation = "2.7.7"
androidxSplashscreen = "1.1.0-rc01"
androidxStartup = "1.2.0-alpha02"
androidxTestEspresso = "3.5.1"
androidxTestJunit = "1.1.5"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTestUiAutomator = "2.3.0"
androidxTracing = "1.3.0-alpha02"
androidxWindow = "1.3.0-beta01"
baselineProfilePlugin = "1.2.3"
composeBom = "2024.04.00-alpha01"
desugar = "2.0.4"
detekt = "1.23.6"
detektCompose = "0.3.13"
dotenvKotlin = "6.4.1"
espresso = "3.6.0-alpha03"
hilt = "2.51.1"
hiltNavigation = "1.2.0"
junit = "5.10.2"
junitPlugin = "1.10.0.0"
kaspresso = "1.5.5"
kotlin = "1.9.23"
kotlinxCollections = "0.3.7"
kotlinxCoroutines = "1.8.0"
kotlinxDatetime = "0.5.0"
kotlinxSerialization = "1.6.3"
ksp = "1.9.23-1.0.20"
ktor = "2.3.10"
leakCanary = "2.13"
licensesPlugin = "0.9.7"
napier = "2.7.1"
okhttp = "5.0.0-alpha.14"
profileinstallerVersion = "1.3.1"
room = "2.6.1"
tomtom = "1.0.0"
truth = "1.4.2"
turbine = "1.1.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotations" }
androidx-benchmark = { group = "androidx.benchmark", name = "benchmark-junit4", version.ref = "androidxBenchmark" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxBenchmark" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "androidxGlance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidxGlance" }
androidx-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "androidxGlancePreview" }
androidx-glance-material = { module = "androidx.glance:glance-material3", version.ref = "androidxGlance" }
androidx-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "androidxGlancePreview" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxSplashscreen" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
androidx-test-espresso-accessibility = { group = "androidx.test.espresso", name = "espresso-accessibility", version.ref = "androidxTestEspresso" }
androidx-test-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "androidxTestEspresso" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "androidxTestEspresso" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestJunit" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxTestUiAutomator" }
androidx-tracing = { module = "androidx.tracing:tracing", version.ref = "androidxTracing" }
androidx-window = { module = "androidx.window:window", version.ref = "androidxWindow" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "composeBom" }
compose-material = { group = "androidx.compose.material3", name = "material3" }
compose-material-windowsize = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-testing = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-testing-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
detekt-rules-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenvKotlin" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
kaspresso = { group = "com.kaspersky.android-components", name = "kaspresso", version.ref = "kaspresso" }
kaspresso-compose = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }
kotlinx-collections = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollections" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-client = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstallerVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
tomtom-geocoder = { group = "com.tomtom.sdk.search", name = "reverse-geocoder", version.ref = "tomtom" }
tomtom-geocoder-online = { group = "com.tomtom.sdk.search", name = "reverse-geocoder-online", version.ref = "tomtom" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-app = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baseline-profile = { id = "androidx.baselineprofile", version.ref = "baselineProfilePlugin" }
benchmark = { id = "androidx.benchmark", version.ref = "androidxBenchmark" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
junit = { id = "de.mannodermaus.android-junit5", version.ref = "junitPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
licenses = { id = "com.jaredsburrows.license", version.ref = "licensesPlugin" }
room = { id = "androidx.room", version.ref = "room" }
