/*
 *    Copyright 2025 Andrey Mukamolov
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package fobo66.valiutchik.api

import org.intellij.lang.annotations.Language

//language=JSON
internal const val SINGLE_CURRENCY = """{
    "date":1754686800,
    "mapobjects":[{
        "id":"27",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  }]
}"""

//language=JSON
internal const val MULTIPLE_CURRENCIES = """{
    "date":1754686800,
    "mapobjects":[{
        "id":"27",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  },
{
        "id":"28",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  }]
}"""

//language=JSON
internal const val SAME_CURRENCIES = """{
    "date":1754686800,
    "mapobjects":[{
        "id":"27",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  },
  {
        "id":"27",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  },
  {
        "id":"28",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  }]
}"""

//language=JSON
internal const val WRONG_JSON = """{
    "date":1754686800,
    "mapobjects":[{
        "blarn":"27",
        "adress":"г. Минск, пр-т Независимости,39",
        "sef_alias":"minsk-pr-t-nezavisimosti-39",
        "city_id":"1",
        "bank_id":"18",
        "bank_name":"Сбер Банк",
        "bank_alias":"bps-sberbank",
        "bank_phone":"a:4:{s:3:\"tel\";s:3:\"148\";s:3:\"vel\";s:17:\"+375-44-514-81-48\";s:3:\"mts\";s:17:\"+375-29-514-81-48\";s:4:\"live\";s:17:\"+375-25-514-81-48\";}",
        "bank_logo":"https:\/\/admin.myfin.by\/images\/company_logos\/bps-sberbank.svg",
        "bank_icon":"https:\/\/admin.myfin.by\/images\/bank_logos\/icons\/sber-mini.svg",
        "working_time":[["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["09:00","19:00"],["00:00","00:00"],["00:00","00:00"]],
        "geo":{"longitude":"27.57662","latitude":"53.91014"},
        "currency":{"date_update":"1754725825","iname":"usd","buy":"2.93","sell":"3.01"},
        "distance":"3628.372",
        "time_to_distance":42289
  }]
}"""

@Language("JSON")
internal const val BANKS = """[
    {
        "fullname": "ЗАО «Альфа-Банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/alfabank.svg",
        "id": "6",
        "logo_path": "https://admin.myfin.by/images/company_logos/alfabank.svg",
        "name": "Альфа Банк",
        "name_in": "Альфа Банке",
        "name_rp": "Альфа Банка",
        "sef_alias": "alfabank",
        "website": "https://www.alfabank.by/"
    },
    {
        "fullname": "ЗАО Банк ВТБ (Беларусь)",
        "icon_path": "https://admin.myfin.by/images/company_logos/bank-vtb.svg",
        "id": "8",
        "logo_path": "https://admin.myfin.by/images/company_logos/bank-vtb.svg",
        "name": "Банк ВТБ (Беларусь)",
        "name_in": "Банке ВТБ (Беларусь)",
        "name_rp": "Банка ВТБ (Беларусь)",
        "sef_alias": "bank-vtb",
        "website": "https://www.vtb.by/"
    },
    {
        "fullname": "ОАО «Банк Дабрабыт»",
        "icon_path": "https://admin.myfin.by/images/company_logos/dabrabyt.svg",
        "id": "9",
        "logo_path": "https://admin.myfin.by/images/company_logos/dabrabyt.svg",
        "name": "Банк Дабрабыт",
        "name_in": "Банке Дабрабыт",
        "name_rp": "Банка Дабрабыт",
        "sef_alias": "dabrabyt",
        "website": "https://bankdabrabyt.by/"
    },
    {
        "fullname": "ОАО «Белагропромбанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/belagroprombank.svg",
        "id": "10",
        "logo_path": "https://admin.myfin.by/images/company_logos/belagroprombank.svg",
        "name": "Белагропромбанк",
        "name_in": "Белагропромбанке",
        "name_rp": "Белагропромбанка",
        "sef_alias": "belagroprombank",
        "website": "https://www.belapb.by/"
    },
    {
        "fullname": "ОАО «АСБ Беларусбанк» ",
        "icon_path": "https://admin.myfin.by/images/company_logos/belarusbank.svg",
        "id": "11",
        "logo_path": "https://admin.myfin.by/images/company_logos/belarusbank.svg",
        "name": "Беларусбанк",
        "name_in": "Беларусбанке",
        "name_rp": "Беларусбанка",
        "sef_alias": "belarusbank",
        "website": "https://belarusbank.by/"
    },
    {
        "fullname": "ОАО «Банк БелВЭБ»",
        "icon_path": "https://admin.myfin.by/images/company_logos/belveb.svg",
        "id": "12",
        "logo_path": "https://admin.myfin.by/images/company_logos/belveb.svg",
        "name": "Банк БелВЭБ",
        "name_in": "Банке БелВЭБ",
        "name_rp": "Банка БелВЭБ",
        "sef_alias": "bvebank",
        "website": "https://www.belveb.by/"
    },
    {
        "fullname": "ОАО «Белгазпромбанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/belgazprombank.svg",
        "id": "13",
        "logo_path": "https://admin.myfin.by/images/company_logos/belgazprombank.svg",
        "name": "Белгазпромбанк",
        "name_in": "Белгазпромбанке",
        "name_rp": "Белгазпромбанка",
        "sef_alias": "belgazprombank",
        "website": "https://belgazprombank.by/"
    },
    {
        "fullname": "ОАО «Белинвестбанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/belinvestbank.svg",
        "id": "14",
        "logo_path": "https://admin.myfin.by/images/company_logos/belinvestbank.svg",
        "name": "Белинвестбанк",
        "name_in": "Белинвестбанке",
        "name_rp": "Белинвестбанка",
        "sef_alias": "belinvestbank",
        "website": "https://www.belinvestbank.by/"
    },
    {
        "fullname": "Открытое акционерное общество «Белорусский народный банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/bnbank.svg",
        "id": "15",
        "logo_path": "https://admin.myfin.by/images/company_logos/bnbank.svg",
        "name": "БНБ-Банк",
        "name_in": "БНБ-Банке",
        "name_rp": "БНБ-Банка",
        "sef_alias": "bnbank",
        "website": "https://bnb.by/"
    },
    {
        "fullname": "ЗАО «БСБ Банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/belswissbank.svg",
        "id": "17",
        "logo_path": "https://admin.myfin.by/images/company_logos/belswissbank.svg",
        "name": "БСБ Банк",
        "name_in": "БСБ Банке",
        "name_rp": "БСБ Банка",
        "sef_alias": "belswissbank",
        "website": "https://www.bsb.by/"
    },
    {
        "fullname": "ОАО «Cбер Банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/bps-sberbank.svg",
        "id": "18",
        "logo_path": "https://admin.myfin.by/images/company_logos/bps-sberbank.svg",
        "name": "Сбер Банк",
        "name_in": "Сбер Банке",
        "name_rp": "Сбер Банка",
        "sef_alias": "bps-sberbank",
        "website": "https://www.sber-bank.by/"
    },
    {
        "fullname": "ЗАО «Нео Банк Азия»",
        "icon_path": "https://admin-global.myfin.by/images/company_logos/neo_logo.svg",
        "id": "19",
        "logo_path": "https://admin-global.myfin.by/images/company_logos/neo_logo.svg",
        "name": "Нео Банк Азия",
        "name_in": "Нео Банке Азия",
        "name_rp": "Нео Банка Азия",
        "sef_alias": "btabank",
        "website": "https://neobank.by/"
    },
    {
        "fullname": "ОАО «СтатусБанк» (бывш. ОАО «Евроторгинвестбанк»)",
        "icon_path": "https://admin.myfin.by/images/company_logos/statusbank.svg",
        "id": "24",
        "logo_path": "https://admin.myfin.by/images/company_logos/statusbank.svg",
        "name": "СтатусБанк",
        "name_in": "СтатусБанке",
        "name_rp": "СтатусБанка",
        "sef_alias": "statusbank",
        "website": "https://stbank.by/"
    },
    {
        "fullname": "ЗАО «МТБанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/mtbank.svg",
        "id": "25",
        "logo_path": "https://admin.myfin.by/images/company_logos/mtbank.svg",
        "name": "МТБанк",
        "name_in": "МТБанке",
        "name_rp": "МТБанка",
        "sef_alias": "mtbank",
        "website": "https://www.mtbank.by/"
    },
    {
        "fullname": "ОАО «Паритетбанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/paritetbank.svg",
        "id": "26",
        "logo_path": "https://admin.myfin.by/images/company_logos/paritetbank.svg",
        "name": "Паритетбанк",
        "name_in": "Паритетбанке",
        "name_rp": "Паритетбанка",
        "sef_alias": "paritetbank",
        "website": "https://www.paritetbank.by/"
    },
    {
        "fullname": "ОАО «Приорбанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/prior.svg",
        "id": "27",
        "logo_path": "https://admin.myfin.by/images/company_logos/prior.svg",
        "name": "Приорбанк",
        "name_in": "Приорбанке",
        "name_rp": "Приорбанка",
        "sef_alias": "priorbank",
        "website": "https://www.priorbank.by/"
    },
    {
        "fullname": "ЗАО «Банк РРБ»",
        "icon_path": "https://admin.myfin.by/images/company_logos/rrb-bank.svg",
        "id": "28",
        "logo_path": "https://admin.myfin.by/images/company_logos/rrb-bank.svg",
        "name": "Банк РРБ",
        "name_in": "Банке РРБ",
        "name_rp": "Банка РРБ",
        "sef_alias": "rrb-bank",
        "website": "https://www.rrb.by/"
    },
    {
        "fullname": "ОАО «Технобанк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/technobank.svg",
        "id": "30",
        "logo_path": "https://admin.myfin.by/images/company_logos/technobank.svg",
        "name": "Технобанк",
        "name_in": "Технобанке",
        "name_rp": "Технобанка",
        "sef_alias": "technobank",
        "website": "https://tb.by/"
    },
    {
        "fullname": "ЗАО «ТК Банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/tkbank.svg",
        "id": "31",
        "logo_path": "https://admin.myfin.by/images/company_logos/tkbank.svg",
        "name": "ТК Банк",
        "name_in": "ТК Банке",
        "name_rp": "ТК Банка",
        "sef_alias": "tkbank",
        "website": "https://www.tcbank.by/"
    },
    {
        "fullname": "ЗАО «Банк «Решение»",
        "icon_path": "https://admin.myfin.by/images/company_logos/reshenie.svg",
        "id": "32",
        "logo_path": "https://admin.myfin.by/images/company_logos/reshenie.svg",
        "name": "Банк Решение",
        "name_in": "Банке Решение",
        "name_rp": "Банка Решение",
        "sef_alias": "reshenie",
        "website": "https://rbank.by/"
    },
    {
        "fullname": "ЗАО «Цептер Банк»",
        "icon_path": "https://admin.myfin.by/images/company_logos/zepterbank.svg",
        "id": "35",
        "logo_path": "https://admin.myfin.by/images/company_logos/zepterbank.svg",
        "name": "Цептер Банк",
        "name_in": "Цептер Банке",
        "name_rp": "Цептер Банка",
        "sef_alias": "zepterbank",
        "website": "https://zepterbank.by/"
    }
]"""

@Language("JSON")
internal const val CURRENCIES = """
[
    {
        "id": "1",
        "iname": "USD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 доллар США",
        "name": "доллар США",
        "name_in": "доллар США",
        "name_rp": "доллара США",
        "sef_alias": "usd",
        "short_name": "$",
        "status": "1",
        "symbol": "$"
    },
    {
        "id": "4",
        "iname": "EUR",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 евро",
        "name": "евро",
        "name_in": "евро",
        "name_rp": "евро",
        "sef_alias": "eur",
        "short_name": "€",
        "status": "1",
        "symbol": "€"
    },
    {
        "id": "5",
        "iname": "RUB",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 российских рублей",
        "name": "российский рубль",
        "name_in": "российский рубль",
        "name_rp": "российского рубля",
        "sef_alias": "rub",
        "short_name": "рос.руб.",
        "status": "1",
        "symbol": "₽"
    },
    {
        "id": "6",
        "iname": "BYN",
        "main_currency": "1",
        "multiplier": "1",
        "multiplierName": "1 белорусский рубль",
        "name": "белорусский рубль",
        "name_in": "белорусский рубль",
        "name_rp": "белорусского рубля",
        "sef_alias": "byn",
        "short_name": "бел.руб",
        "status": "1",
        "symbol": "р."
    },
    {
        "id": "7",
        "iname": "UAH",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 гривен",
        "name": "гривна",
        "name_in": "гривну",
        "name_rp": "гривны",
        "sef_alias": "uah",
        "short_name": "грн.",
        "status": "1",
        "symbol": "¥"
    },
    {
        "id": "8",
        "iname": "PLN",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 польских злотых",
        "name": "польский злотый",
        "name_in": "польский злотый",
        "name_rp": "польского злотого",
        "sef_alias": "pln",
        "short_name": "zł",
        "status": "1",
        "symbol": "zł"
    },
    {
        "id": "9",
        "iname": "EURUSD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 евро - доллар",
        "name": "евро - доллар",
        "name_in": "евро - доллар",
        "name_rp": "евро - доллара",
        "sef_alias": "eurusd",
        "short_name": "евро - доллар",
        "status": "2",
        "symbol": "eurusd"
    },
    {
        "id": "10",
        "iname": "USDRUB",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 доллар США - российские рубли",
        "name": "доллар США - российские рубли",
        "name_in": "доллары США - российские рубли",
        "name_rp": "долларов США - российских рублей",
        "sef_alias": "usdrub",
        "short_name": "доллар - рос.руб",
        "status": "2",
        "symbol": "usdrub"
    },
    {
        "id": "11",
        "iname": "EURRUB",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 евро - российские рубли",
        "name": "евро - российские рубли",
        "name_in": "евро - российские рубли",
        "name_rp": "евро - российских рублей",
        "sef_alias": "eurrub",
        "short_name": "евро - рос.руб",
        "status": "2",
        "symbol": "eurrub"
    },
    {
        "id": "12",
        "iname": "GBP",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 фунт стерлингов",
        "name": "фунт стерлингов",
        "name_in": "фунты стерлингов",
        "name_rp": "фунтов стерлингов",
        "sef_alias": "gbp",
        "short_name": "фунт",
        "status": "1",
        "symbol": "gbp"
    },
    {
        "id": "13",
        "iname": "CNY",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 китайских юаней",
        "name": "китайский юань",
        "name_in": "китайский юань",
        "name_rp": "китайских юаней",
        "sef_alias": "cny",
        "short_name": "юань",
        "status": "1",
        "symbol": "cny"
    },
    {
        "id": "14",
        "iname": "KZT",
        "main_currency": "0",
        "multiplier": "1000",
        "multiplierName": "1000 тенге",
        "name": "тенге",
        "name_in": "тенге",
        "name_rp": "тенге",
        "sef_alias": "kzt",
        "short_name": "тенге",
        "status": "1",
        "symbol": "kzt"
    },
    {
        "id": "15",
        "iname": "CHF",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 швейцарский франк",
        "name": "швейцарский франк",
        "name_in": "швейцарский франк",
        "name_rp": "швейцарского франка",
        "sef_alias": "chf",
        "short_name": "франк",
        "status": "1",
        "symbol": "chf"
    },
    {
        "id": "16",
        "iname": "CZK",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 чешских крон",
        "name": "чешская крона",
        "name_in": "чешскую крону",
        "name_rp": "чешской кроны",
        "sef_alias": "czk",
        "short_name": "чешская крона",
        "status": "1",
        "symbol": "czk"
    },
    {
        "id": "17",
        "iname": "AUD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 австралийский доллар",
        "name": "австралийский доллар",
        "name_in": "австралийский доллар",
        "name_rp": "австралийского доллара",
        "sef_alias": "aud",
        "short_name": "австралийский доллар",
        "status": "3",
        "symbol": "aud"
    },
    {
        "id": "18",
        "iname": "BGN",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 болгарский лев",
        "name": "болгарский лев",
        "name_in": "болгарский лев",
        "name_rp": "болгарского льва",
        "sef_alias": "bgn",
        "short_name": "болгарский лев",
        "status": "3",
        "symbol": "bgn"
    },
    {
        "id": "19",
        "iname": "DKK",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 датских крон",
        "name": "датская крона",
        "name_in": "датскую крону",
        "name_rp": "датской кроны",
        "sef_alias": "dkk",
        "short_name": "датская крона",
        "status": "3",
        "symbol": "dkk"
    },
    {
        "id": "20",
        "iname": "IRR",
        "main_currency": "0",
        "multiplier": "100000",
        "multiplierName": "100000 иранских риал",
        "name": "иранский риал",
        "name_in": "иранский риал",
        "name_rp": "иранского риала",
        "sef_alias": "irr",
        "short_name": "иранский риал",
        "status": "3",
        "symbol": "irr"
    },
    {
        "id": "21",
        "iname": "ISK",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 исландских крон",
        "name": "исландская крона",
        "name_in": "исландскую крону",
        "name_rp": "исландской кроны",
        "sef_alias": "isk",
        "short_name": "исландская крона",
        "status": "3",
        "symbol": "isk"
    },
    {
        "id": "22",
        "iname": "JPY",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 йен",
        "name": "йена",
        "name_in": "йену",
        "name_rp": "йене",
        "sef_alias": "jpy",
        "short_name": "йена",
        "status": "3",
        "symbol": "jpy"
    },
    {
        "id": "24",
        "iname": "CAD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 канадский доллар",
        "name": "канадский доллар",
        "name_in": "канадский доллар",
        "name_rp": "канадского доллара",
        "sef_alias": "cad",
        "short_name": "канадский доллар",
        "status": "3",
        "symbol": "cad"
    },
    {
        "id": "25",
        "iname": "KWD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 кувейтский динар",
        "name": "кувейтский динар",
        "name_in": "кувейтский динар",
        "name_rp": "кувейтского динара",
        "sef_alias": "kwd",
        "short_name": "кувейтский динар",
        "status": "3",
        "symbol": "kwd"
    },
    {
        "id": "26",
        "iname": "MDL",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 молдавских леев",
        "name": "молдавский лей",
        "name_in": "молдавский лей",
        "name_rp": "молдавского лея",
        "sef_alias": "mdl",
        "short_name": "молдавский лей",
        "status": "3",
        "symbol": "mdl"
    },
    {
        "id": "27",
        "iname": "NOK",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 норвежских крон",
        "name": "норвежская крона",
        "name_in": "норвежскую крону",
        "name_rp": "норвежской кроны",
        "sef_alias": "nok",
        "short_name": "норвежская крона",
        "status": "3",
        "symbol": "nok"
    },
    {
        "id": "28",
        "iname": "XDR",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 СДР (Специальные права заимствования)",
        "name": "СДР (Специальные права заимствования)",
        "name_in": "СДР (Специальные права заимствования)",
        "name_rp": "СДР (Специальные права заимствования)",
        "sef_alias": "xdr",
        "short_name": "СДР",
        "status": "3",
        "symbol": "xdr"
    },
    {
        "id": "29",
        "iname": "SGD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 сингапурcкий доллар",
        "name": "сингапурcкий доллар",
        "name_in": "сингапурcкий доллар",
        "name_rp": "сингапурcкого доллара",
        "sef_alias": "sgd",
        "short_name": "сингапурcкий доллар",
        "status": "3",
        "symbol": "sgd"
    },
    {
        "id": "30",
        "iname": "KGS",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 сом",
        "name": "сом",
        "name_in": "сом",
        "name_rp": "сома",
        "sef_alias": "kgs",
        "short_name": "сом",
        "status": "3",
        "symbol": "kgs"
    },
    {
        "id": "31",
        "iname": "TRY",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 турецких лир",
        "name": "турецкая лира",
        "name_in": "турецкую лиру",
        "name_rp": "турецкой лиры",
        "sef_alias": "try",
        "short_name": "турецкая лира",
        "status": "1",
        "symbol": "try"
    },
    {
        "id": "32",
        "iname": "SEK",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 шведских крон",
        "name": "шведская крона",
        "name_in": "шведскую крону",
        "name_rp": "шведской кроны",
        "sef_alias": "sek",
        "short_name": "шведская крона",
        "status": "3",
        "symbol": "sek"
    },
    {
        "id": "33",
        "iname": "GEL",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 грузинский лари",
        "name": "грузинский лари",
        "name_in": "грузинский лари",
        "name_rp": "грузинского лари",
        "sef_alias": "gel",
        "short_name": "грузинский лари",
        "status": "1",
        "symbol": "gel"
    },
    {
        "id": "34",
        "iname": "VND",
        "main_currency": "0",
        "multiplier": "100000",
        "multiplierName": "100000 вьетнамский донг",
        "name": "вьетнамский донг",
        "name_in": "вьетнамский донг",
        "name_rp": "вьетнамского донга",
        "sef_alias": "vnd",
        "short_name": "донг",
        "status": "1",
        "symbol": "vnd"
    },
    {
        "id": "35",
        "iname": "AMD",
        "main_currency": "0",
        "multiplier": "1000",
        "multiplierName": "1000 армянский драм",
        "name": "армянский драм",
        "name_in": "армянский драм",
        "name_rp": "армянского драма",
        "sef_alias": "amd",
        "short_name": "драм",
        "status": "1",
        "symbol": "amd"
    },
    {
        "id": "36",
        "iname": "BRL",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 бразильский реал",
        "name": "бразильский реал",
        "name_in": "бразильский реал",
        "name_rp": "бразильского реала",
        "sef_alias": "brl",
        "short_name": "реал",
        "status": "1",
        "symbol": "brl"
    },
    {
        "id": "37",
        "iname": "NZD",
        "main_currency": "0",
        "multiplier": "1",
        "multiplierName": "1 новозеландский доллар",
        "name": "новозеландский доллар",
        "name_in": "новозеландский доллар",
        "name_rp": "новозеландского доллара",
        "sef_alias": "nzd",
        "short_name": "новозеландский доллар",
        "status": "1",
        "symbol": "nzd"
    },
    {
        "id": "38",
        "iname": "INR",
        "main_currency": "0",
        "multiplier": "100",
        "multiplierName": "100 индийская рупия",
        "name": "индийская рупия",
        "name_in": "индийскую рупию",
        "name_rp": "индийской рупии",
        "sef_alias": "inr",
        "short_name": "рупия",
        "status": "1",
        "symbol": "inr"
    },
    {
        "id": "39",
        "iname": "AED",
        "main_currency": "0",
        "multiplier": "10",
        "multiplierName": "10 дирхам ОАЭ",
        "name": "дирхам ОАЭ",
        "name_in": "дирхам ОАЭ",
        "name_rp": "дирхама ОАЭ",
        "sef_alias": "aed",
        "short_name": "дирхам",
        "status": "1",
        "symbol": "aed"
    }
] 
"""
